// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Diagnostics;
using System.Linq;
using System.Windows;
using System.Windows.Media;

namespace todo.Model
{
    public partial class Todo : INotifyPropertyChanged
    {
        private string task;
        private bool isCompleted;

        public string TodoId { get; set; }
        public string Task
        {
            get { return task; }
            set
            {
                task = value;
                PropertyChanged?.Invoke(this, new PropertyChangedEventArgs("Task"));
            }
        }
        public bool IsCompleted
        {
            get { return isCompleted; }
            set
            {
                isCompleted = value;
                using (var db = new TodoContext())
                {
                    var item = db.Todos.Find(TodoId);
                    item.isCompleted = value;
                    db.SaveChanges();

                }
                PropertyChanged?.Invoke(this, new PropertyChangedEventArgs("IsCompleted"));
                PropertyChanged?.Invoke(this, new PropertyChangedEventArgs("Blur"));
            }
        }

        [NotMapped]
        public SolidColorBrush Blur
        {
            get
            {
                if (IsCompleted)
                {
                    return (SolidColorBrush)Application.Current.Resources["CompletedOpacity"];
                }
                return (SolidColorBrush)Application.Current.Resources["TextBoxBackground"];
            }
        }

        public event PropertyChangedEventHandler? PropertyChanged;

    }

}